# Setup
title:        sedrickkeh.github.io
tagline:      Projects, thoughts, and other random stuff.
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Sedrick Keh
  url:        https://github.com/sedrickkeh/sedrickkeh.github.io 

# Gems
gems:
  - jekyll-paginate

# Others
markdown: kramdown

# Collections:
collections:
  projects:
    output: true
    permalink: /:collection/:title